urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template
from bridgebill import views

# For serving static files on development environment
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.login),
    #url(r'^$', 'django.contrib.auth.views.login', { 'template_name': 'index.html' }),
    url(r'^login-error$', views.login_error),

    url(r'^home/$', views.home),
    url(r'^home/details/(?P<person_id>[a-zA-Z0-9_-]+)/$', views.home_details),
    url(r'^bill/details/(?P<view_status>[a-zA-Z0-9_-])/(?P<overall_bill_id>[a-zA-Z0-9_-]+)/$', views.specific_bill_details),
    url(r'^user/sign-up/$', views.user_signup),
    url(r'^user/forgot-password/$', 'django.contrib.auth.views.password_reset',{ 'template_name':'forgot-password.html', 'email_template_name':'email_templates/password_reset.txt', 'post_reset_redirect': '/user/forgot-password/password-reset-initiated/' } ),
    url(r'^user/forgot-password/password-reset-initiated/$', 'django.contrib.auth.views.password_reset_done',{ 'template_name':'forgot-password-confirmation.html' } ),
    url(r'^user/forgot-password/password-reset-form/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',{ 'template_name':'forgot-password-actual-form.html', 'post_reset_redirect': '/user/forgot-password/password-reset-complete/' } ),
    url(r'^user/forgot-password/password-reset-complete/$', 'django.contrib.auth.views.password_reset_complete',{ 'template_name':'forgot-password-success.html' } ),
    #url(r'^record-bill/$', views.record_bill_option),
    url(r'^record-bill/$', views.record_bill),
    url(r'^record-bill/equal-split/$', views.record_bill_equal_split),
    url(r'^record-bill/unequal-split/$', views.record_bill_unequal_split),
    url(r'^settle-payment/$', views.settle_payment),
    url(r'^settle-payment-ajax/$', views.settle_payment_ajax),
    url(r'^settle-payment/complete/$', views.settle_payment_complete),
    url(r'^who-i-owe/$', views.who_i_owe),
    url(r'^who-owes-me/$', views.who_owes_me),
    url(r'^transaction-history/$', views.transaction_history),
    url(r'^transaction-history/details/(?P<person_id>[a-zA-Z0-9_-]+)/$', views.transaction_history_details),
    url(r'^my-profile/$', views.my_profile),
    url(r'^my-profile/my-friends/$', views.my_friends),
    url(r'^my-profile/my-friends/edit-friend/(?P<userfriend_id>[a-zA-Z0-9_-]+)/$', views.edit_friend), # AJAX
    url(r'^my-profile/my-friends/delete-friend/(?P<userfriend_id>[a-zA-Z0-9_-]+)/$', views.delete_friend), # AJAX
    url(r'^my-profile/my-friends/add-friend/$', views.add_friend), # AJAX
    url(r'^my-profile/change-password/$', views.change_password),
    url(r'^my-profile/change-password-success/$', views.change_password_success),
    url(r'^logout/$', views.logout_user),
    url(r'^about-us/$', direct_to_template, { 'template': 'about-us.html' }),
    url(r'^feedback/$',  views.feedback),
    url(r'^feedback/confirmation$', direct_to_template, { 'template': 'feedback_success.html' }),
    url(r'^contact-us/$', direct_to_template, { 'template': 'contact-us.html' }),

    # For making changes to table
    #url(r'^change_table/$',  views.change_table_heroku),

    url(r'', include('social_auth.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

# For serving static files on development environment
urlpatterns += staticfiles_urlpatterns()

bridgebill/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms 
from django.forms import ModelForm
from datetime import date

CURRENCY_CHOICES = (
        ('AGR', 'Argentina Peso (AGR)'),
        ('AUD', 'Australia Dollar (AUD)'),
        ('BRL', 'Brazil Real (BRL)'),
        ('CAD', 'Canada Dollar (CAD)'),
        ('CHF', 'Switzerland Franc (CHF)'),
        ('CLP', 'Chile Peso (CLP)'),
        ('CNY', 'China Yuan (CNY)'),
        ('CRC', 'Costa Rica Colon (CRC)'),
        ('CZK', 'Czech Republic Koruna (CZK)'),
        ('DKK', 'Denmark Krone (DKK)'),
        ('EUR', 'European Union Euro (EUR)'),
        ('GBP', 'United Kingdom Pound GBP)'),
        ('HKD', 'Hong Kong Dollar (HKD)'),
        ('HRK', 'Croatia Kuna (HRK)'),
        ('IDR', 'Indonesia Rupiah (IDR)'),
        ('ILS', 'Israel New Shekel (ILS)'),
        ('INR', 'India Rupee (INR)'),
        ('ISK', 'Iceland Krona (ISK)'),
        ('JPY', 'Japan Yen (JPY)'),
        ('KRW', 'South Korea Won (KRW)'),
        ('MXN', 'Mexico Peso (MXN)'),
        ('MYR', 'Malaysia Ringgit (MYR)'),
        ('NOK', 'Norway Krone (NOK)'),
        ('NZD', 'New Zealand Dollar (NZD)'),
        ('PEN', 'Peru Sol (PEN)'),
        ('PHP', 'Philippines Pesos (PHP)'),
        ('PKR', 'Pakistan Rupee (PKR)'),
        ('PLN', 'Poland Zloty (PLN)'),
        ('RON', 'Romania Lei (RON)'),
        ('RUB', 'Russia Ruble (RUB)'),
        ('SEK', 'Sweden Krona (SEK)'),
        ('SGD', 'Singapore Dollar (SGD)'),
        ('THB', 'Thailand Baht (THB)'),
        ('TWD', 'Taiwan New Dollar (TWD)'),
        ('UAH', 'Ukraine Hryvnia (UAH)'),
        ('USD', 'United States Dollar (USD)'),
        ('VEB', 'Venezuela Bolivar (VEB)'),
        ('VND', 'Vietnam Dong (VND)'),
        ('ZAR', 'South Africa Rand (ZAR)'),
        )

class UserProfile(models.Model):
    userprofile_id = models.CharField(max_length=50)
    user = models.OneToOneField(User)
    currency = models.CharField(max_length=5, choices=CURRENCY_CHOICES, blank=True)

    def __unicode__(self):
        return 'User: ' + self.user.first_name + ' ' + self.user.last_name

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ('currency', )

FRIEND_DELETED_CHOICES = (
        ('N', 'No'),
        ('Y', 'Yes'),
        )

class UserFriend(models.Model):
    userfriend_id = models.CharField(max_length=50)
    user_profile = models.ForeignKey(UserProfile)
    friend_email = models.EmailField(max_length=75)
    friend_name = models.CharField(max_length=60)
    friend_created_date = models.DateField(auto_now_add=True)
    friend_deleted = models.CharField(max_length=1, choices=FRIEND_DELETED_CHOICES)

    def __unicode__(self):
        return 'Lender: ' + self.user_profile.user.email + ' is a friend of Borrower: ' + self.friend_email

class UserFriendForm(ModelForm):
    class Meta:
        model = UserFriend
        fields = ('friend_name', 'friend_email')

class Bill(models.Model):
    overall_bill_id = models.CharField(max_length=50)
    lender = models.ForeignKey(UserProfile)
    date = models.DateField()
    description = models.CharField(max_length=30)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=30, choices=CURRENCY_CHOICES, blank=False, default='SGD')
    remarks = models.CharField(max_length=300, blank=True)
    created_date = models.DateField(auto_now_add=True)
    
    def __unicode__(self):
        return  str(self.lender) + ' created a bill for ' + str(self.description) + ' an amount of: ' + str(self.amount)

class PartialBillForm(ModelForm):
    date = forms.DateField(initial=date.today().strftime('%d/%m/%Y'), input_formats=['%d/%m/%Y'], widget=forms.TextInput(attrs={ 'readOnly': 'readOnly' }))
    class Meta:
        model = Bill
        fields = ('date', 'amount', 'currency', 'description', 'remarks')

BILL_CLEARED_CHOICES = (
        ('N', 'No'),
        ('Y', 'Yes'),
        )

BILL_DELETED_CHOICES = (
        ('N', 'No'),
        ('Y', 'Yes'),
        )

class BillDetails(models.Model):
    billdetail_id = models.CharField(max_length=50)
    bill = models.ForeignKey(Bill)
    borrower = models.ForeignKey(UserFriend)
    individual_amount = models.DecimalField(max_digits=10, decimal_places=2)
    bill_cleared = models.CharField(max_length=1, choices=BILL_CLEARED_CHOICES)
    bill_cleared_date = models.DateField()
    remarks = models.CharField(max_length=300, blank=True)
    individual_bill_created_date = models.DateField(auto_now_add=True)
    bill_deleted = models.CharField(max_length=1, choices=BILL_DELETED_CHOICES)

    def __unicode__(self):
        return str(self.bill.lender) + ' lent ' + str(self.borrower.friend_name) + ' for ' + str(self.bill.description)

class PartialBillDetailsForm(ModelForm):
    date = forms.DateField(initial=date.today().strftime('%d/%m/%Y'), input_formats=['%d/%m/%Y'], widget=forms.TextInput(attrs={ 'readOnly': 'readOnly' }))
    class Meta:
        model = BillDetails
        fields = ('date', 'remarks')

class Feedback(models.Model):
    name = models.CharField(blank=True, max_length=60)
    email = models.EmailField(blank=True, max_length=75)
    message = models.TextField()
    created_date = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return str(self.name) + '(' + str(self.email) + ')' + ' left a message'

class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback 

# Start - Signals for sending email on user registration and for adding user as own friend
from django.dispatch import receiver
from social_auth.signals import socialauth_registered

from django.conf import settings
if 'mailer' in settings.INSTALLED_APPS:
    from mailer import send_mail
else:
    from django.core.mail import send_mail
from django.template.loader import get_template
from django.template import Context
account_creation_txt = get_template('email_templates/account_creation.txt')
account_creation_html = get_template('email_templates/account_creation.html')


# Start - Common function for creating UUIDs
import uuid
def create_uuid():
    return str(uuid.uuid4())
# End - Common function for creating UUIDs

# Start - Creating unique UserProfile ID
def create_userprofile_id():
    check_counter = True
    while check_counter is True:
        userprofile_id = 'up_' + create_uuid()
        try: 
            user_profile = UserProfile.objects.get(userprofile_id=userprofile_id)
            check_counter = True
        except:
            check_counter = False
    return userprofile_id
# End - Creating unique UserProfile ID


# Start - Creating unique UserFriend ID
def create_userfriend_id():
    check_counter = True
    while check_counter is True:
        userfriend_id = 'uf_' + create_uuid()
        try: 
            user_friend = UserFriend.objects.get(userfriend_id=userfriend_id)
            check_counter = True
        except:
            check_counter = False
    return userfriend_id
# End - Creating unique UserFriend ID

def new_users_handler(sender, user, response, details, **kwargs):
    user.is_new = True

    # Start - Send Email
    context = Context( {} )
    subject, to = 'Welcome to BridgeBill', user.email
    account_creation_txt_content = account_creation_txt.render(context)
    account_creation_html_content = account_creation_html.render(context)
    send_mail(subject, account_creation_txt_content, settings.DEFAULT_FROM_EMAIL, [ to ])
    # End - Send Email
    
    # Start - Add User as his own friend
    userprofile_id = create_userprofile_id()
    user_profile = UserProfile(userprofile_id=userprofile_id, user=user)
    user_profile.save()

    userfriend_id = create_userfriend_id()
    user_own_friend = UserFriend(userfriend_id=userfriend_id, user_profile=user_profile, friend_email=user.email, friend_name=user.first_name+' '+user.last_name, friend_deleted='N')
    user_own_friend.save()
    # End - Add User as his own friend

    return False

socialauth_registered.connect(new_users_handler, sender=None)
# End - Signals for sending email on user registration and for adding user as own friend

bridgebill/forms.py
from django import forms

CHOICES = (
(0, 'a'),
(1, 'b'),
(2, 'c'),
)

class MyForm(forms.Form):
    letters = forms.MultipleChoiceField(
            choices=CHOICES, 
            label="x", 
            required=True) 

bridgebill/templates/contact-us.html
{% extends 'index.html' %}
{% block title %}BridgeBill - Contact Us{% endblock %}
{% block body %}
<div id="index">
    <div id="index_header">
        <h1><span><a href="/"><strong class="logo">BridgeBill</strong> - Split Bills and Keep Track of Your Expenses</a></span></h1>
    </div>
    <div id="footer_content">
        <h2>Contact Us</h2>
        <p class="last_para">I can be reached here: <a href="mailto: arpitrai@gmail.com">Gmail</a>, <a href="http://www.twitter.com/arpitrai">Twitter</a> or <a href="http://wwww.linkedin.com/in/arpitrai">LinkedIn</a></p>
    </div>
    <div id="index_push">
    </div>
</div>
<div id="index_footer">
    <ul class="footer_links"> 
        <li><a href="/about-us/">About Us</a></li>
        <li><a href="/feedback/">Feedback</a></li>
        <!--<li><a href="/contact-us/">Contact Us</a></li>-->
    </ul> 
</div>
{% endblock %}

bridgebill/templates/feedback_success.html
{% extends 'about-us.html' %}
{% block title %}BridgeBill - Feedback{% endblock %}
{% block footer_content_django %}
<h2>Feedback</h2>
<p class="last_para">Thank you for your feedback!</p> 
{% endblock %}

bridgebill/templates/forgot-password-confirmation.html
{% extends 'index.html' %}
{% block title %}BridgeBill - Password Reset{% endblock %}
{% block body %}
<div id="index">
    <div id="index_header">
        <h1><span><a href="/"><strong class="logo">BridgeBill</strong> - Split Bills and Keep Track of Who Owes What</a></span></h1>
    </div>
    <div id="forgot_password">
        <div class="sub_header">
            <span class="title">Password Reset</span>
        </div>
        <div class="forgot_password_form" id="forgot_password_confirmation">
            <ul>
                <li>
                    <span class="message">An email has been sent to you with the password reset instructions. If you do not get the email in the next 5 minutes, please contact <a href="mailto:admin@bridgebill.com">admin@bridgebill.com</a>.</span>
                </li>
            </ul>
        </div>
    </div>
    <div id="index_push">
    </div>
</div>
<div id="index_footer">
    <ul class="footer_links"> 
        <li><a href="/about-us/">About Us</a></li>
        <li><a href="/feedback/">Feedback</a></li>
        <!--<li><a href="/contact-us/">Contact Us</a></li>-->
    </ul> 
</div>
{% endblock %}

bridgebill/templates/forgot-password.html
{% extends 'index.html' %}
{% block title %}BridgeBill - Password Reset{% endblock %}
{% block body %}
<div id="index">
    <div id="index_header">
        <h1><span><a href="/"><strong class="logo">BridgeBill</strong> - Split Bills and Keep Track of Who Owes What</a></span></h1>
    </div>
    <div id="forgot_password">
        <div class="sub_header">
            <span class="title">Reset Password</span>
        </div>
        <div class="forgot_password_form">
            <ul>
                <li>
                    <span class="message">Please enter your email address below so that we can send you instructions that will help you reset your password.</span>
                </li>
                <li>
                    <form id="forgot_password_form" name="forgot_password" action="" method="post">
                        {% csrf_token %}
                        <ul>
                            {% if form.email.errors %}
                            <li id="forgot_password_error">
                                <span>Email does not exist! Please try again.</span>
                            </li>
                            {% endif %}
                            <li>
                                <label class="index" for="id_email">Your Email </label>
                                {{ form.email }}
                            </li>
                            <li class="last">
                                <button id="save" type="submit">Reset Password</button>
                            </li>
                        </ul>
                    </form>
                </li>
            </ul>
        </div>
    </div>
    <div id="index_push">
    </div>
</div>
<div id="index_footer">
    <ul class="footer_links"> 
        <li><a href="/about-us/">About Us</a></li>
        <li><a href="/feedback/">Feedback</a></li>
        <!--<li><a href="/contact-us/">Contact Us</a></li>-->
    </ul> 
</div>
{% endblock %}

bridgebill/templates/my-friends.html
{% extends "home.html" %}
{% load humanize %}
{% load currency_symbol %}
{% block title %}BridgeBill - My Friends{% endblock %}
{% block content %}
<div id="content_one">
<p class="page_header">My Friends</p>
{% if my_friends %}
    <ul class="base_ul_overview" id="my_friends">
        <li style="display: none;"></li>
        {% for friend in my_friends %}
        <li>
            <span class="mock_border">
                <span class="name">{{ friend.friend_name }}</span>
                <span class="email">{{ friend.friend_email }}</span>
            </span>
            <span style="display: none;" class="last edit"><button class="edit_friend" value="{{ friend.userfriend_id }}">Edit</button></span>
            <span style="display: none;" class="last delete"><button class="delete_friend" value="{{ friend.userfriend_id }}">Delete</button></span>
            <span class="ajax_loading"><img src="{{ STATIC_URL }}images/ajax-loader.gif" alt="Processing" /></span>
        </li>
        {% endfor %}
    </ul>
    <ul class="my_friends add_remove_button">
        <li>
            <button class="add_friend">Add Friend</button> 
        </li>
    </ul>
{% else %}
    <p class="my_friends default_message">None yet. Click the button below to add your contacts.</p>
    <ul class="base_ul_overview" id="my_friends">
        <li style="display: none;"></li>
    </ul>
    <ul class="my_friends add_remove_button">
        <li>
            <button class="add_friend">Add Friend</button> 
        </li>
    </ul>
{% endif %}
</div>
{% endblock %}

bridgebill/templates/record-bill-option.html
{% extends "home.html" %}
{% block title %}BridgeBill - Record Bill{% endblock %}
{% block content %}
<div id="content_one">
    <form id="record_bill_option" name="record_bill_option" action="" method="post">
        {% csrf_token %}
        <ul>
            <li>
                <label>Equal Split<input type="radio" checked="checked" name="record_bill_option" value="equal_split" /></label>
            </li>
            <li>
                <label>Un-Equal Split<input type="radio" name="record_bill_option" value="unequal_split" /></label>
            </li>
            <li class="last">
                <button id="save" type="submit">Proceed</button>
            </li>
        </ul>
    </form>
</div>
{% endblock %}

bridgebill/templates/record-bill-unequal-split.html
{% extends "home.html" %}
{% block title %}BridgeBill - Record Bill{% endblock %}
{% block content %}
<div id="content_one">
    <form id="unequal_split" name="unequal_split" action="" method="post">
        {% csrf_token %}
        <ul>
            <li>
                <label for="id_date">Date <span class="date_format_small">(dd/mm/yyyy)</span></label>
                {{ bill_form.date }}
            </li>
            <li>
                <label for="id_description">Description </label>
                {{ bill_form.description }}
            </li>
            <li>
                <label for="id_amount">Total Amount </label>
                {{ bill_form.amount }}
            </li>
            <li>
                <label for="id_currency">Currency </label>
                {{ bill_form.currency }}
            </li>
            <li>
                <label for="id_total_people">No. of People </label>
                <input type="text" name="total_people" id="id_total_people" />
            </li>
            <li class="make_inline">
                <label for="id_debtors">Split Among </label>
                <table id="unequal_split_people_table" name="unequal_split_people_table">
                    <thead>
                        <th class="name">Name</th>
                        <th class="number">Paid For</th>
                        <th class="amount">Amount</th>
                    </thead>
                    <tbody>
                        {% for my_friend in my_friends %}
                            <tr>
                                <td class="name"> 
                                    <input type="hidden" class="people" />
                                    <select name="borrower_{{ forloop.counter0 }}" id="id_borrower_{{ forloop.counter0 }}">
                                        <option value=""></option>
                                        {% for my_friend in my_friends %}
                                        <!--<option value="{{ my_friend.friend_email }}">{{ my_friend.friend_name }} {% if userprofile_object.user.email == my_friend.friend_email %}{% if userprofile_object.user.first_name or userprofile_object.user.last_name %}(Me){% else %}Me{% endif %}{% endif %}</option>-->
                                        <option value="{{ my_friend.friend_email }}">{% if userprofile_object.user.email == my_friend.friend_email %}Me{% else %}{{ my_friend.friend_name }}{% endif %} - {{ my_friend.friend_email }}</option>
                                        {% endfor %}
                                    </select>
                                </td>
                                <td class="number">
                                    <select name="number_of_people_{{ forloop.counter0 }}" id="id_number_of_people_{{ forloop.counter0 }}">
                                        <option value=""></option>
                                        <option value="1">1 person</option>
                                        <option value="2">2 people</option>
                                        <option value="3">3 people</option>
                                        <option value="4">4 people</option>
                                        <option value="5">5 people</option>
                                        <option value="Other">Other</option>
                                    </select>
                                </td>
                                <td class="amount">
                                    <input type="text" name="borrower_amount_{{ forloop.counter0 }}" id="id_borrower_amount_{{ forloop.counter0 }}"/>
                                </td>
                                <td class="remove_placeholder">
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <span class="friend_checked">Please select a friend!</span>
            </li>
            <li>
                <button class="add_friend">Add Friend</button> 
            </li>
            <li class="last">
                <button id="save" type="submit">Save</button>
            </li>
        </ul>
    </form>
</div>
{% endblock %}

bridgebill/templates/record-payment-1.html
{% extends "home.html" %}
{% block title %}BridgeBill - Record Payment{% endblock %}
{% block content %}
<div id="content_one">
    <form name="record_payment" id="record_payment" action="/record-payment-full/" method="post">
        {% csrf_token %}
        <ul>
            <li>
                <label for="id_date">Date </label>
                {{ payment_form.date }}
            </li>
            <li>
                <label for="id_paid_to">Settle With </label>
                <span id="paid_to">{{ person_name }}</span>
            </li>
            <li>
                <label id="bills" for="id_description">Bills </label>
                <table class="base_table" id="record_payment_table">
                    <thead>
                        <tr>
                            <th class="check_bill"><input type="checkbox" /></th>
                            <th class="date">Date</th>
                            <th class="description">Description</th>
                            <th class="amount">Amount</th>
                            <th class="flag">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for bill in lender_bill_details %}
                        <tr>
                            <td class="check_bill"><input type="checkbox" name="billdetail_id" value="{{ bill.billdetail_id }}" /></td>
                            <td class="date">{{ bill.bill.date|date:"jS M Y" }}</td>
                            <td class="description">{{ bill.bill.description }}</td>
                            <td class="amount">S$ {{ bill.individual_amount }}</td>
                            <td class="flag red"><span>I Owe</span></td>
                        </tr>
                        {% endfor %}
                        {% for bill in borrower_bill_details %}
                        <tr>
                            <td class="check_bill"><input type="checkbox" name="billdetail_id" value="{{ bill.billdetail_id }}" /></td>
                            <td class="date">{{ bill.bill.date|date:"jS M Y" }}</td>
                            <td class="description">{{ bill.bill.description }}</td>
                            <td class="amount">S$ {{ bill.individual_amount }}</td>
                            <td class="flag green"><span>Owes Me</span></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </li>
            <li>
                <label for="id_remarks">Remarks </label>
                {{ payment_form.remarks }}
            </li>
            <li class="last">
                <button id="save" type="submit">Save</button>
            </li>
        </ul>
        <input type="hidden" name="lender" id="id_lender" value="{{ lender.user.email }}" />
        <input type="hidden" name="description" id="id_description" value="Value" />
    </form>
</div>
{% endblock %}

bridgebill/templates/settle-payment-ajax.html
{% load humanize %}
{% load currency_symbol %}
{% if not blank_element %}
<form name="record_payment" id="record_payment" action="/settle-payment/complete/" method="post">
    {% csrf_token %}
    <ul>
        <li>
            <label for="id_date">Date <span class="date_format_small">(dd/mm/yyyy)</span></label>
            {{ payment_form.date }}
        </li>
        <!--<li>
            <label for="id_paid_to">Settle With </label>
            <span id="paid_to">{{ person_name }}</span>
        </li>-->
        <li>
            <label id="bills" for="id_description">Bills </label>
            <table class="base_table" id="record_payment_table">
                <thead>
                    <tr>
                        <th class="check_bill"><input type="checkbox" /></th>
                        <th class="date">Date</th>
                        <th class="description">Description</th>
                        <th class="amount">Amount</th>
                        <th class="flag">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for bill in lender_bill_details %}
                    <tr>
                        <td class="check_bill"><input type="checkbox" name="billdetail_id" value="{{ bill.billdetail_id }}" /></td>
                        <td class="date">{{ bill.bill.date|date:"jS M Y" }}</td>
                        <td class="description">{{ bill.bill.description }}</td>
                        <td class="amount red"><span>{{ bill.bill.currency|currency }} {{ bill.individual_amount|intcomma }}</span></td>
                        <td class="flag">I Owe</td>
                    </tr>
                    {% endfor %}
                    {% for bill in borrower_bill_details %}
                    <tr>
                        <td class="check_bill"><input type="checkbox" name="billdetail_id" value="{{ bill.billdetail_id }}" /></td>
                        <td class="date">{{ bill.bill.date|date:"jS M Y" }}</td>
                        <td class="description">{{ bill.bill.description }}</td>
                        <td class="amount green"><span>{{ bill.bill.currency|currency }} {{ bill.individual_amount|intcomma }}</span></td>
                        <td class="flag">Owes Me</td>
                    </tr>
                    {% endfor %}
                    <span class="bills_checked">Please select a bill!</span>
                    <table class="base_table" id="net_bill">
                        <tbody>
                            {% for key, value in overall.items %}
                            <tr class="net">
                                <td class="check_bill"></td>
                                <td class="date"></td>
                                <td class="description">Net</td>
                                <td class="amount {% if value.1 == "+ve" %}green{% else %}{% if value.1 == "-ve" %}red{% else %}{% if value.1 == "zero" %}blue{% endif %}{% endif %}{% endif %}"><span>{{ key|currency }} {{ value.0|intcomma }}</span></td>
                                <td class="flag">{% if value.1 == "+ve" %}Owes Me{% else %}{% if value.1 == "-ve" %}I Owe{% else %}{% if value.1 == "zero" %}Even{% endif %}{% endif %}{% endif %}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </tbody>
            </table>
        </li>
        <li>
            <label for="id_remarks">Remarks <span class="date_format_small">(optional)</span></label>
            {{ payment_form.remarks }}
        </li>
        <li class="last">
            <button id="save" type="submit">Mark as Settled</button>
        </li>
    </ul>
    <input type="hidden" name="person" id="id_person" value="{{ person_email }}" />
    <input type="hidden" name="person_name" id="id_person_name" value="{{ person_name }}" />
    <input type="hidden" name="description" id="id_description" value="Value" />
</form>
{% endif %}